### ISSUE TITLE
[QUESTION] - How is the `TransactionMobileSdkService` service used

### ISSUE THREAD

**Issue by fabio-nettis** [pfpayments/typescript-sdk#1]
## What is my question about?

We are currently re-building our mobile application and configuring the mobile web view integration mode for our client application and struggling with the implementation of the `paymentFormUrl(credentials: string, options?: any)` method.

### The issue

Nowhere in the documentation is stated what this functions `credential` parameter really is. At this point we have basically tried any combination of possible credential data whatsoever.

- Only the applicationUserKey as is
- Only the applicationUserKey as base 64
- {userId}:{applicationUserKey} as base 64
- Created a HMAC SHA512 signature using the crypto module

### A useful answer would be ..

If you could elaborate what kind of credential is required inside this method.

**Comment by fabio-nettis** [comment]
Anyone?

**Comment by theodorspringwallee** [comment]
Dear [fabio-nettis](https://github.com/fabio-nettis)

I forwarded your questions to our devs.

**Comment by fabio-nettis** [comment]
@theodorspringwallee Thank you. Looking forward to any answer provided.

**Comment by fabio-nettis** [comment]
@theodorspringwallee Any updates on this?

**Comment by theodorspringwallee** [comment]
Dear [fabio-nettis](https://github.com/fabio-nettis)

We have a developer assigned to it. We will let you know, when we can provide any updates on this.

**Comment by fabio-nettis** [comment]
## Update

I have done some research in the original wallee documentation and have found out how the service is used:

> Create Transaction Credentials
> This operation allows to create transaction credentials to delegate temporarily the access to the web service API for this particular transaction.
>
> `POST /api/transaction/createTransactionCredentials`

### Usage

The secret is later needed on the mobile device delegating the web view to fetch the possible payment actions from the merchant server. When using the typescript SDK you can request the client secret like this:

```typescript
const { PostFinanceCheckout } = require("postfinancecheckout");
const PostfinanceAPI = PostFinanceCheckout.api;

async function getCredentials(transactionId: string): Promise<string> {
  const transactionService = new PostfinanceAPI.TransactionService();
  
  const { body: credentials } = await transactionService.createTransactionCredentials(
     "MY_SPACE_ID",
      transactionId
  );

  return credentials;
}
```

**Comment by theodorspringwallee** [comment]
Dear [fabio-nettis](https://github.com/fabio-nettis)

Thank you for this input. So I guess you don't need further help from us here?

I appreciate a quick answer.

**Comment by fabio-nettis** [comment]
@theodorspringwallee Yeah. No additional help needed. Thank you anyway!
