### ISSUE TITLE
What about es6 support?

### ISSUE THREAD

**Issue by nimloth05** [pfpayments/typescript-sdk#2]
What are the plans to support ES6 modules?

**Comment by theodorspringwallee** [comment]
Dear [nimloth05](https://github.com/nimloth05)

Our developers will discuss this. We will let you know, when we have further information for you.

Best regards

**Comment by theodorspringwallee** [comment]
Dear [nimloth05](https://github.com/nimloth05)

We currently do not support the ES6 modules.

Please can you tell us, which issues you have with the current SDK, respectively why you would need the ES6 modules support?

Thank you for your answers.

Best regards

**Comment by theodorspringwallee** [comment]
Dear [nimloth05](https://github.com/nimloth05)

We appreciate your answer, about our previous comment.

Best regards

**Comment by vttn** [comment]
Closing issue because of none responsiveness.
