### ISSUE TITLE
ERROR TypeError: postfinancecheckout_1.PostFinanceCheckout.api.TransactionPaymentPageService is not a constructor

### ISSUE THREAD

**Issue by miedziana** [pfpayments/typescript-sdk#3]
I am trying to configure Postfinance Checkout API following the example from your README file.
I am using Angular 13 and Typescript 4.4.4

The project compiles, after I changed my tsconfig.json file to change compilerOptions.module: "commonjs" from "esnext".
However it still doesn't seem to work - I get the following error:
**ERROR TypeError: postfinancecheckout_1.PostFinanceCheckout.api.TransactionPaymentPageService is not a constructor**

I think it must be some configuration/compatibility issue - any idea what might be the problem there?

**Comment by theodorspringwallee** [comment]
Dear [miedziana](https://github.com/miedziana)

Please can you contact therefore the PostFinance support (https://www.postfinance.ch/en/private/support/hotline.html) and provide them your project files (with the mentioned tsconfig.json as well your SDK code) to them.

Many thanks and best regards
