### ISSUE TITLE
Add documentation / example for WebhookListenerService and WebhookUrlService

### ISSUE THREAD

**Issue by tobias47n9e** [pfpayments/typescript-sdk#4]
At the moment it seems unclear what the classes `WebhookListenerService` and `WebhookUrlService` are there for. Would it be possible to add docs and an example to both classes? I am trying to find an example of how to listen to a Webhook defined in a Postfinance space and if the SDK can perhaps help with what kind of JSON type to expect in the body when the webhook calls my application.

**Comment by tobias47n9e** [comment]
@theodorspringwallee Thanks for the detailed explanation. I think what I was looking for in the SDK, was an interface like this one for the body of the webhook event:

```ts
export interface WebhookEvent {
    eventId: number,
    entityId: number,
    listenerEntityId: number,
    listenerEntityTechnicalName: 'Transaction' | string, // List all possible entities or link to enum?
    spaceId: number,
    webhookListenerId: number,
    timestamp: string;
}
```

Is it possible that that is missing from the SDK at the moment?

**Comment by theodorspringwallee** [comment]
Dear [tobias47n9e](https://github.com/tobias47n9e)

I couldn't find any reference of a method of the SDK, that is receiving and parsing the raw content that is sent from our webhooks to the target URL, where your script is behind.

Sent content from our webhooks (example):
```
{
"eventId": 138997445,
"entityId": 63842795,
"listenerEntityId": 1472041829003,
"listenerEntityTechnicalName":
"Transaction"
"spaceId": 28435,
"webhookListenerId": 285948,
"timestamp":
"2022-08-2407:53:40+0000'
}
```

At the moment you need to parse the incoming content manually. For example with a JSON parser.

If you want, I can ask our plugins team to add such a WebhookReceiver.ts service, that you could use there on your interface, where you are receiving the webhooks?

Thank you for your feedback.

Best regards

**Comment by tobias47n9e** [comment]
@theodorspringwallee I actually use the TypedJson library to parse the incoming webhook event:

```ts
import { jsonMember, jsonObject } from "typedjson";

@jsonObject
export class WebhookEvent {
    @jsonMember
    eventId: number;

    @jsonMember
    entityId: number;

    @jsonMember
    listenerEntityId: number;

    @jsonMember
    listenerEntityTechnicalName: 'Transaction' | string;

    @jsonMember
    spaceId: number;

    @jsonMember
    webhookListenerId: number;

    @jsonMember
    timestamp: string;
}
```

It is not a lot of code that needs to be implemented using either a typescript interface or this class for "typedjson", but it is kind of missing from the documentation what the payload of the request is. I also couldn't find the payload and header information here: https://checkout.postfinance.ch/doc . 

So maybe it doesn't really need a service but just some docs how to handle the webhook event:

- What is the payload and what are the headers of the request and how do they change (if they do), if the event is tried multiple times
- What kind of response codes can be sent back
- Which response codes deactivate the webhook

In general the webhook docs seem to me would warrant an own chapter in the docs, because many things are not explained in detail:

- When can the first webhook event be expected after it being triggered
- How many times and in which time intervals will it be retried, if the server is not reachable?

**Comment by theodorspringwallee** [comment]
Dear [tobias47n9e](https://github.com/tobias47n9e)

Here we have a documentation, about the payload of the webhooks: https://checkout.postfinance.ch/en/doc/webhooks#_integration_details

Here you see how often and in which time span failed webhooks are retried:
![image](https://user-images.githubusercontent.com/85299706/208945988-6186257f-1d38-421b-913e-cc5b8f5db768.png)

After that you would receive an email to your defined email on your space, where you need to take manual actions.

Does this answer your questions?

Best regards

**Comment by tobias47n9e** [comment]
@theodorspringwallee Thanks for the link. I hadn't seen the chapter before. In this case my issue is all resolved now.
