### ISSUE TITLE
[ISSUE] - HTTP Status Code 303 when using `LightboxService.javascriptUrl`

### ISSUE THREAD

**Issue by fabio-nettis** [pfpayments/typescript-sdk#6]
**Describe the bug**

We use the PF Payments Typescript SDK in our production and development API instances to create Lightbox URL's that can be requested by our shop's server-side and passed down to the client to render a script tag to start the checkout process.

### Integration details

```ts
const { PostFinanceCheckout } = require("postfinancecheckout");

const config = {
  space_id: process.env.PF_SPACE_ID,
  user_id: process.env.PF_USER_ID,
  api_secret: process.env.PF_SECRET,
};

async function createLightboxURL(transactionCreate, transactionId = null) {
  try {
    const transaction = await service("api::payment.payment").createTransaction(transactionCreate, transactionId);

    // Create a new instance of the Postfinance API transaction lightbox service
    const LightboxService = new PostfinanceAPI.TransactionLightboxService(config);
    const { body: IFrameURL } = await LightboxService.javascriptUrl(config.space_id, transaction.id);

    return { id: transaction.id, url: IFrameURL };
  } catch (err) {
    service("api::sentry.sentry").sendError(err);
    throw new Error(err.message);
  }
}
```

Since a couple of days the development integration suddenly stopped working when a client requests the creation of the Lightbox URL. The status code 303 "See Other" is returned without any context or documentation whatsoever. This only occurs for the development instance that targets a different space than production.

----

**Expected behavior**

The Lightbox URL should be created without any issues or this status code should at least be properly documented inside the API documentation, but this specific status code returns 0 matches inside the whole docs.

Additional context

The same integration still works when targeting our production space. This only occurs when the development space is used, I have checked the Space and User ID's as well as the validity of the secret multiple times now and they are absolutely valid.

**Comment by theodorspringwallee** [comment]
Dear [fabio-nettis](https://github.com/fabio-nettis)

Many thanks for reporting this issue.

Please, can you provide us your production and development space IDs?

Best regards

**Comment by fabio-nettis** [comment]
@theodorspringwallee Sure, here you go:

- Development: #32475
- Production: #28184

**Comment by theodorspringwallee** [comment]
Dear [fabio-nettis](https://github.com/fabio-nettis)

Thanks for your feedback, we will let you know, when we have news on this.

Best regards

**Comment by fabio-nettis** [comment]
@theodorspringwallee Any update on this? This issue is breaking down our whole development flow and because spaces cost real-world money, creating a new space and testing it is also not a viable solution to us.

**Comment by theodorspringwallee** [comment]
Dear [fabio-nettis](https://github.com/fabio-nettis), I asked our Product Owner if we have updates on this.

Best regards

**Comment by theodorspringwallee** [comment]
Dear [fabio-nettis](https://github.com/fabio-nettis), our portal developers checked the logs.

And there were no requests for the dev-space '32475' about the lightbox URL at all.

It's maybe up to your (local?) development environment, that has issues with the connection to the portal?
(You told with production it's working)

To give you further support, our developers need the full request and response details (with headers and body) of your lightbox URL call.

Many thanks for your answer.

Best regards

**Comment by fabio-nettis** [comment]
@theodorspringwallee After further inspection the 303 Status code is generated earlier in the processing chain when calling the following method:

```js
async function createTransaction(transactionCreate, transactionId = null) {
  const transactionService = new PostfinanceAPI.TransactionService(config);

  if (!transactionId) {
   // the error occurs here
    const { body } = await transactionService.create(config.space_id, transactionCreate);
    return body;
  }

  const { body } = await transactionService.read(config.space_id, transactionId);
  return body;
}
```

This explains why there were no requests for the dev-space '32475' about the lightbox URL at all. Still, error code 303 is returned, not documented and we are still stuck with correctly working code in production but not in development.

**Comment by theodorspringwallee** [comment]
Dear [fabio-nettis](https://github.com/fabio-nettis)

I will ask our developers again to check the logs in the 32475 space about transaction create requests.

Best regards

**Comment by theodorspringwallee** [comment]
Dear [fabio-nettis](https://github.com/fabio-nettis)

We couldn't find any logs regarding this issue you mentioned. You're told in your response you received an error code 303.

Are in the response also some header values as 'cf-ray'? With this, our developers could find maybe something in some other logs.

Thanks for your feedback.

Best regards

**Comment by fabio-nettis** [comment]
@theodorspringwallee Here is the response headers that are returned for the 303 Status code result.

```jsonc
// statusCode: 303
// statusMessage: 'See Other'
// body: undefined
{
  "Date": "Fri, 14 Jul 2023 06:52:47 GMT",
  "Content-Length": "0",
  "Connection": "keep-alive",
  "X-SVID": "0b98cacee02a78ae7",
  "Set-Cookie": "**REDACTED**",
  "Set-Cookie": "**REDACTED**",
  "Expires": "Thu, 01 Jan 1970 00:00:00 GMT",
  "Location": "/user/login?session-timeout",
  "CF-Cache-Status": "DYNAMIC",
  "Server": "cloudflare",
  // here is the cf-ray header you asked for
  "CF-RAY": "7e67d84bbb13bae5-MXP"
}
```

**Comment by theodorspringwallee** [comment]
Many thanks [fabio-nettis](https://github.com/fabio-nettis)

We will let you know, when we have updates for you.

Best regards

**Comment by fabio-nettis** [comment]
@theodorspringwallee Sorry for bothering you again, is there any progress on this whatsoever? We are kind of stuck here.

**Comment by theodorspringwallee** [comment]
Dear [fabio-nettis](https://github.com/fabio-nettis)

Currently, our developers are still working on (we get some logs, but the issue is missing).

So we are looking further on.

Best regards

**Comment by theodorspringwallee** [comment]
Dear [fabio-nettis](https://github.com/fabio-nettis)

Finally, we can say, that we can't find your issue in our logs.

Possibly the issue lies on your testing systems (proxy server between, local environment settings etc.).

At least, we do not have any other customer complaining about this specific space-related issue.

For further support, you can contact the PF support directly: https://www.postfinance.ch/de/support/hotline.html

And share with them your environments, access credentials and code.

Best regards

**Comment by fabio-nettis** [comment]
Seems strange to me. But I will close this issue for now and re-open it if I am directed here again by postfinance.
