### ISSUE TITLE
Package cannot be used

### ISSUE THREAD

**Issue by srudin** [pfpayments/typescript-sdk#9]
We are trying to integrate https://www.npmjs.com/package/postfinancecheckout into our solution but that seems to be way harder than expected. After adding the package reference there are a large number of (different) errors showing up similar to:

`BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
        - install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "crypto": false }`

What is the correct way to get this package working?

**Comment by theodorspringwallee** [comment]
Dear [srudin](https://github.com/srudin)

We will check this.

Best regards

**Comment by thibault-mambour** [comment]
Hi @srudin , as mentioned in our Readme, we are highly recommending (and supporting) to use this SDK in server-side application. Do you think it is something you could change in your implementation ?

**Comment by srudin** [comment]
There has been a misunderstanding, we have switched to https://github.com/pfpayments/java-sdk and use it in our backend, thank you.
